spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sda_my_app_student
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

        logging:
          level:
            org:
              hibernate:
                tool:
                  hbm2ddl: debug